# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 17:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('is_right', models.BooleanField(default=False, verbose_name='Is right')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_created=datetime.datetime(2017, 5, 10, 17, 24, 37, 319465, tzinfo=utc), verbose_name='Date published')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('accessible_for', models.ManyToManyField(related_name='accessible_quizzes', to='auth.Group', verbose_name='Accessible for')),
            ],
        ),
        migrations.CreateModel(
            name='QuizFinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_created=datetime.datetime(2017, 5, 10, 17, 24, 37, 318964, tzinfo=utc), verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('mark', models.PositiveIntegerField(verbose_name='Mark')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_quizzes', to='quizzes.Quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='questions', to='quizzes.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.Question', verbose_name='Question'),
        ),
    ]
