# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 12, 16, 47, 49, 784017, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='quizfinished',
            name='started_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 12, 16, 47, 49, 783542, tzinfo=utc), verbose_name='Started at'),
        ),
    ]
