# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20170512_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 14, 20, 32, 35, 456217, tzinfo=utc), verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='quizfinished',
            name='started_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 14, 20, 32, 35, 455745, tzinfo=utc), verbose_name='Started at'),
        ),
    ]
