"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-hn(nq5o5ytiyad*+5!m65*f6dc3of*(%4f&qqa+-b2#lh(34h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['194.87.93.29', '127.0.0.1', 'buzaza.ddns.net']

INTERNAL_IPS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'font_awesome',
    'social_django',
    'crispy_forms',
    'taggit',

    'core',
    'quizzes',
    'polls',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LOCALE_PATHS = (
    BASE_DIR + '/mysite/locale/',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR + '/static/'


LOGIN_URL = '/login/'


# Crispy-forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# Emailss in file
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR + '/emails' # change this to a proper location


# Django-taggit
TAGGIT_CASE_INSENSITIVE = True


# Social auth
SOCIAL_AUTH_GITHUB_KEY = '625b88739db6420c7d29'
SOCIAL_AUTH_GITHUB_SECRET = 'e09748d61b309cd67272ee789bd550b2c0a3f5db'

SOCIAL_AUTH_BITBUCKET_OAUTH2_KEY = 'A37gZLnJbPAnwQk2gd'
SOCIAL_AUTH_BITBUCKET_OAUTH2_SECRET = 'fPcNXn6UGsHARB2xNHVrtzZptTrhmXHc'

SOCIAL_AUTH_VK_OAUTH2_KEY = '6026033'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'pNXkJnxGFr9tpwY4Zmkf'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '326229261707-jf3n2o5fjjbm7q8ic6t59fdtrdijfh89.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '39hbuSgpFEPBM3CnZo1pT638'

SOCIAL_AUTH_YANDEX_OAUTH2_KEY = '318c689d873b4a01948d92e12eb3ae11'
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = 'f0c47bc5c17f42eabc38d75ce9113de6'

SOCIAL_AUTH_MAILRU_OAUTH2_KEY = '753902'
SOCIAL_AUTH_MAILRU_OAUTH2_SECRET = 'bcd40699c7f849d1bfaa4640d8d5964d'

SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ['username', 'email']

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',

    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.bitbucket.BitbucketOAuth2',
    'social_core.backends.vk.VKOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.yandex.YandexOAuth2',
    # 'social_core.backends.mailru.MailruOAuth2',
    )