# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170512_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 14, 20, 32, 35, 457540, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
