# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170514_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 5, 15, 14, 37, 45, 874560, tzinfo=utc), verbose_name='Date published'),
        ),
    ]
