# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('projects', '0002_auto_20170514_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helplink',
            options={'verbose_name': 'Help link', 'verbose_name_plural': 'Help links'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name': "User's project", 'verbose_name_plural': "User's projects"},
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='courses.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='project',
            name='help_links',
            field=models.ManyToManyField(blank=True, to='projects.HelpLink', verbose_name='Help links'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optional_projects', to='projects.Project', verbose_name='Main project'),
        ),
    ]
